apiVersion: samples.k8s-dotnet-controller-sdk/v1
kind: PostgreSQL
metadata:
  name: pg1
  namespace: default
spec:
  engine:
    version: 14
  services:
    primary:
      type: LoadBalancer
  credentials: pg1-credentials
  initialcatalog: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: pg1-credentials
  namespace: default
data:
  userid: Ym9vcg==
  password: YWNudG9yUFJFU1RPIQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg1-config
data:
  # instance: 172.23.212.180,5432 # Local
  instance: pg1-internal-svc,5432 # K8s
  catalog: postgres