apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresdbs.samples.k8s-dotnet-controller-sdk
spec:
  group: samples.k8s-dotnet-controller-sdk
  scope: Namespaced
  names:
    plural: postgresdbs
    singular: postgresdb
    kind: PostgresDB
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "A Postgres Database"
          properties:
            spec:
              type: object
              properties:
                dbName:
                  type: string
                configMap:
                  type: string
                credentials:
                  type: string
              required: ["dbName", "configMap", "credentials"]
