apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.samples.k8s-dotnet-controller-sdk
spec:
  group: samples.k8s-dotnet-controller-sdk
  scope: Namespaced
  names:
    plural: postgresqls
    singular: postgresql
    kind: PostgreSQL
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "A Postgres Instance"
          properties:
            spec:
              type: object
              properties:
                engine:
                  type: object
                  properties:
                    version:
                      type: integer
                services:
                  type: object
                  properties:
                    primary:
                      type: object
                      properties:
                        type:
                          type: string
                        port:
                          type: integer
                credentials:
                  type: string
                initialCatalog:
                  type: string
              required: ["engine", "services", "credentials", "initialCatalog"]
