apiVersion: samples.k8s-dotnet-controller-sdk/v1
kind: PostgreSQL
metadata:
  name: pg1
  namespace: default
spec:
  engine:
    version: 14
  services:
    primary:
      type: LoadBalancer
      port: "25432"
  credentials: pg1-credentials
  initialCatalog: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: pg1-credentials
  namespace: default
data:
  userid: Ym9vcg==
  password: YWNudG9yUFJFU1RPIQ==